#!/bin/bash

#########################
# NPX Utils
#########################

function npxCreateReactAppTypescript() {
  pnpm create next-app --typescript
}

function npxInstallTailwind() {
	pnpm install -D tailwindcss postcss autoprefixer
	npx tailwindcss init -p
}

