#!/bin/bash

#########################
# NPX Utils
#########################

function npxCreateReactAppTypescript() {
  npm create next-app --typescript
}

function npxInstallTailwind() {
	npm install -D tailwindcss postcss autoprefixer
	npx tailwindcss init -p
}

